#!/usr/bin/env ruby

require 'bio/gadgets'

module Bio
  class Gadgets < Thor
    
    register(Bio::Gadget::Fq1l, 'fq1l', 'fq1l [COMMAND]', 'Tools for oneline-fastq; fq1l in the alias')
    register(Bio::Gadget::STRT, 'strt', 'strt [COMMAND]', 'Tools for STRT RNAseq; strt is the alias')
    
  end
end

Bio::Gadgets.start
